### ISSUE TITLE
No implementation for HttpRequestRecordWriter<?> was bound

### ISSUE THREAD

**Issue by PGVIJAY** [vy/hrrs#56]
Get following exception in running distiller. 

Exception in thread "main" com.google.inject.ConfigurationException: Guice configuration errors:

1) [Guice/MissingImplementation]: No implementation for HttpRequestRecordReader<?> was bound.

Requested by:
1  : Distiller.<init>(Distiller.java:55)
      \_ for 2nd parameter
     while locating Distiller

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

2) [Guice/MissingImplementation]: No implementation for HttpRequestRecordWriter<?> was bound.

Requested by:
1  : Distiller.<init>(Distiller.java:55)
      \_ for 3rd parameter
     while locating Distiller

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

2 errors

======================
Full classname legend:
======================
Distiller:               "com.vlkan.hrrs.distiller.cli.Distiller"
HttpRequestRecordReader: "com.vlkan.hrrs.api.HttpRequestRecordReader"
HttpRequestRecordWriter: "com.vlkan.hrrs.api.HttpRequestRecordWriter"
========================
End of classname legend:
========================

        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1127)
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1087)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1139)
        at com.vlkan.hrrs.distiller.cli.Distiller.main(Distiller.java:153)
        at com.vlkan.hrrs.distiller.base64.Base64Distiller.main(Base64Distiller.java:27)

**Comment by PGVIJAY** [comment]
Changing the return types in Base64DistillerModule seems to fix the problem - 
public HttpRequestRecordReader<?> provideReader(Config config) 
public HttpRequestRecordWriter<?> provideWriter(Config config)

**Comment by vy** [comment]
@PGVIJAY, released 0.7.1 with this fix. Artifacts should appear momentarily in the Maven Central.
